class CardHeaderStyles:

    BASIC_BROWN = 'BASIC_BROWN'
    WHITE_FONT_BLACK_BG = 'WHITE_FONT_BLACK_BG'
    BLACK_FONT_GRAY_BG = 'BLACK_FONT_GRAY_BG'
    GRAY_FONT_WHITE_BG = 'GRAY_FONT_WHITE_BG'


class NumberHeaderStyles:
    BASIC_BLACK = 'BASIC_BLACK'
    GRAY = 'GRAY'
    RED = 'GRAY'
